apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: YWRtaW4=
  POSTGRES_PASSWORD: YWRtaW4zMDkzZWMxNzY1YTg5MzUyNmMzZDhmMmViNzQzZGQyMzA2YTBhMWMyY2QyNTQ5MTA3NTBmZWZlOWMxZWJlZg==
